server:
  port: 8000
  servlet:
    context-path: /rbac

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
logging:
  level:
    com:
      plf:
        rbac:
          mapper: debug

mybatis-plus:
  type-aliases-package: com.plf.rbac.entity
  global-config:
    db-config:
      id-type:  AUTO
      table-underline:  true
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
